version: 2
updates:
  - package-ecosystem: cargo
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "04:00"
    open-pull-requests-limit: 5
    groups:
      patch:
        patterns:
          - "*"
        update-types:
          - patch
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "04:00"
    open-pull-requests-limit: 5
    groups:
      actions:
        patterns:
          - "*"
